service: cvs-svc-test-results

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3006
  dynamodb:
    start:
      port: 8014
      inMemory: true
      migrate: true
      seed: true
      noStart: false
      host: 127.0.0.1
    seed:
      test-results:
        sources:
          - table: cvs-local-test-results
            sources: [./tests/resources/test-results.json]
    stages:
      - dev
      - test

functions:
  getTestResults:
    environment:
      BRANCH: local
    handler: src/handler.handler
    events:
      - http:
          path: test-results
          method: post
      - http:
          path: test-results/{systemNumber}
          method: put
          request:
            parameters:
              paths:
                systemNumber: true
      - http:
          path: test-results/{systemNumber}
          method: get
          request:
            parameters:
              paths:
                systemNumber: true
              query:
                status: false
                fromDateTime: false
                toDateTime: false
  getTestResultsByTesterStaffId:
    environment:
      BRANCH: local
    handler: src/functions/getTestResultsByTesterStaffId.getTestResultsByTesterStaffId
    events:
      - http:
          path: test-results/getTestResultsByTesterStaffId
          method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-results
        AttributeDefinitions:
          - AttributeName: vin
            AttributeType: S
          - AttributeName: testResultId
            AttributeType: S
          - AttributeName: testerStaffId
            AttributeType: S
          - AttributeName: systemNumber
            AttributeType: S
          - AttributeName: testStartTimestamp
            AttributeType: S
        KeySchema:
          - AttributeName: vin
            KeyType: HASH
          - AttributeName: testResultId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: TesterStaffIdIndex
            KeySchema:
              - AttributeName: testerStaffId
                KeyType: HASH
              - AttributeName: testStartTimestamp
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - testEndTimestamp
                - testTypes
                - vrm
                - numberOfSeats
                - testStationPNumber
                - vehicleType
                - vin
                - preparerId
                - testStatus
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
          - IndexName: SysNumIndex
            KeySchema:
              - AttributeName: systemNumber
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
