functions:
- postTestResults:
    method: POST
    path: /test-results
    proxy: null
    function: postTestResults
- getTestResultsBySystemNumber:
    method: GET
    path: /test-results/{+proxy}
    proxy: :systemNumber
    function: getTestResultsBySystemNumber
- getTestResultsByTesterStaffId:
    method: GET
    path: /test-results/getTestResultsByTesterStaffId
    proxy: null
    function: getTestResultsByTesterStaffId
dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://localhost:8004
      convertEmptyValues: true
    table: cvs-local-test-results
  local-global:
    params:
      region: localhost
      endpoint: http://localhost:8000
      convertEmptyValues: true
    table: cvs-local-global-test-results
  remote:
    params:
      convertEmptyValues: true
    table: cvs-${BRANCH}-test-results
serverless:
  basePath: /${BRANCH}
  port: 3006
endpoints:
  local-global:
    params:
      apiVersion: '2015-03-31'
      region: eu-west-1
      endpoint: http://localhost:4000
    functions:
      getTestTypesById:
        name: cvs-svc-global-dev-getTestTypesById
      getTestNumber:
        name: cvs-svc-global-dev-generateTestNumber
  remote:
    params:
      apiVersion: '2015-03-31'
    functions:
      getTestTypesById:
        name: test-types-${BRANCH}
      getTestNumber:
        name: test-number-${BRANCH}
